version: '3.8'

services:
  # Backend API (Production)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: citycamp_backend_prod
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/citycamp_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY:-production-secret-key-change-me}
      - ENVIRONMENT=production
      - DEBUG=False
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"  # Expose on port 8000 for load balancer
    depends_on:
      - postgres
      - redis
    networks:
      - citycamp_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL Database (Production)
  postgres:
    image: postgres:15-alpine
    container_name: citycamp_postgres_prod
    environment:
      POSTGRES_DB: citycamp_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - citycamp_network
    restart: unless-stopped

  # Redis for Celery (Production)
  redis:
    image: redis:7-alpine
    container_name: citycamp_redis_prod
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - citycamp_network
    restart: unless-stopped

  # Celery Worker (Production)
  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: citycamp_celery_worker_prod
    command: celery -A app.celery worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/citycamp_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY:-production-secret-key-change-me}
      - ENVIRONMENT=production
      - DEBUG=False
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgres
      - redis
    networks:
      - citycamp_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  citycamp_network:
    driver: bridge
